FROM eclipse-temurin:21-alpine

ARG USER_ID
ARG GROUP_ID

RUN addgroup -g ${GROUP_ID} -S vectoriadb; \
adduser -u ${USER_ID} -S vectoriadb -G vectoriadb; \
mkdir /vectoriadb; \
chown -R vectoriadb:vectoriadb /vectoriadb

EXPOSE 9090
EXPOSE 5005

USER vectoriadb

RUN mkdir /vectoriadb/logs; \
mkdir /vectoriadb/config; \
mkdir /vectoriadb/indexes; \
mkdir /vectoriadb/bin

COPY build/libs/*.jar /vectoriadb/bin/
VOLUME ["/vectoriadb/logs", "/vectoriadb/config", "/vectoriadb/indexes"]
WORKDIR /vectoriadb
ENTRYPOINT ["java", "-Dvectoriadb.server.base-path=/vectoriadb" ,"-cp", "/vectoriadb/bin/*", \
"--enable-preview", "-Dvectoriadb.log.dir=/vectoriadb/logs", "-Dvectoriadb.server.debug=true", \
"jetbrains.vectoriadb.server.ApplicationInitializer"]